server:
  port: 8082

spring:
  application:
    name: customer
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    showSql: true
    hibernate:
      ddlAuto: update
    generateDdl: true
  h2:
    console:
      enabled: true
      path: /h2/

# ./mvnw spring-boot:run -Dspring-boot.run.arguments="--user=your_user --pass=your_pass --cluster=your_cluster"